steps:   
  #Run Software Composition Analysis  (SCA security scan)  using Snyk
  - name: 'ubuntu'
    entrypoint: bash
    args: 
        - '-c'
        - |-
          apt-get update
          apt-get -y install maven 
          SNYK_TOKEN=${_SNYK_TOKEN}
          export SNYK_TOKEN
          mvn snyk:test -fn 
          snyk test --severity-threshold=medium --json | snyk-to-html -o results.html || true

    id: Snyk SCA
  - name: snyk/snyk-cli:npm
    args:
      - '-c'
      - |-
        snyk config set api=${_SNYK_TOKEN}
        set -o pipefail
        snyk test --severity-threshold=medium --json | snyk-to-html -o results.html || true
    id: Create HTML artifact
    entrypoint: bash
artifacts:
  objects:
    location: 'gs://sushil-snyk-scan'
    paths:
      - results.html
